### ISSUE TITLE
关于WPF中数据库问题

### ISSUE THREAD

**Issue by ZlxmChen** [buaa-soft-summer/soft-summer-2022#10]
希望对ItemsControl内容与本地数据库绑定，只需增删与读取操作，哪种实现方式相对较方便？以及有没有推荐的教程或blog（检索结果不尽人意

**Comment by havesomecolo** [comment]
教程挺多的吧：http://t.zoukankan.com/3xiaolonglong-p-9723926.html

**Comment by Yuan-Hou** [comment]
控件应该不能直接和数据库绑定，你需要在程序里实现数据库的增、删、查，并将取得的相应数据的变量绑定到控件上。

我那个时候连接数据库用的不是C#自带的标准库，而是Github上找到的一个ORM项目叫SqlSugar，它能帮你把数据库里面的记录和编程语言里的对象对应起来。在Github上能找到它的文档，想安装这个包在Nuget上直接搜就能找到。

https://github.com/donet5/SqlSugar

**Comment by ZlxmChen** [comment]
好的，谢谢
