### ISSUE TITLE
Android动画

### ISSUE THREAD

**Issue by TerryRy** [buaa-soft-summer/soft-summer-2022#11]
请问平移动画怎么做出比较复杂的折线呢，我的animate().translationYBy和animate().translationXBy似乎只能各用一次啊

**Comment by woarthur** [comment]
可以考虑使用贝塞尔曲线效果，
https://blog.csdn.net/a_liuhaiyang/article/details/70256583/
https://www.jb51.net/article/247450.htm
https://cloud.tencent.com/developer/article/2027669
