### ISSUE TITLE
微信小程序图片渲染层网络错误

### ISSUE THREAD

**Issue by lsysyy** [buaa-soft-summer/soft-summer-2022#13]
就是简单的<image src="/images/your name.jpeg"></image>一句话
然后图片无法显示，调试器说是渲染层网络错误Failed to load local image resource /images/your%20name.jpeg 
 the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error) 
用其他图片也是一样的问题

**Comment by RyouonRitsu** [comment]
看一下這些
[小程序运行报错：[渲染层网络层错误] Failed to load local image resource ... the server responded with a status of 500](https://blog.csdn.net/m0_67392931/article/details/123305140)
[[渲染层网络层错误] Failed to load local image resource /images/poster](https://www.jianshu.com/p/94d4048c46df)

**Comment by jongjyh** [comment]
[也可以看看这个](https://developers.weixin.qq.com/community/develop/doc/00046a4434084846a5a93de6651c00)

**Comment by lsysyy** [comment]
已经解决了谢谢助教！
