### ISSUE TITLE
unity人物在进入随机生成的地牢和切换房间时卡死

### ISSUE THREAD

**Issue by SAGADESU** [buaa-soft-summer/soft-summer-2022#14]
想要脚本实现的功能是在人物切换到不同房间时，mainCamera也切换到对应房间，但是在进入不同场景时会卡死
private void OnTriggerEnter2D(Collider2D other)
    {
        if(other.CompareTag("player"))
        {
            CameraController.instance.ChangeTarget(transform);
        }
    }
初步判断是这里出了问题

**Comment by SAGADESU** [comment]
![77b18d6e884d6e6e2b977ddf5103edc](https://user-images.githubusercontent.com/111098074/184858530-33188d9b-6daa-4e9a-86f2-878e8771115f.jpg)

**Comment by RyouonRitsu** [comment]
請使用cinemachine插件的多相機切換功能 設置好虛擬相機的位置後使用SetActive方法即可進行相機切換 同一時間保持僅有一個虛擬相機處於Active即可
