### ISSUE TITLE
unity背景颜色覆盖整个摄像头

### ISSUE THREAD

**Issue by SAGADESU** [buaa-soft-summer/soft-summer-2022#15]
https://user-images.githubusercontent.com/111098074/184897512-30fb240b-f8ba-4ffe-8ea6-8c07ffe1eb6a.mp4

在scene窗口可以得到人物正常运动，摄像头位置也正常改变，但是摄像头画面被背景颜色完全覆盖，一开始会闪一下

**Comment by RyouonRitsu** [comment]
尝试调整CM vcam的CinemachineVirtualCamera组件的Body的Binding Mode改为World Space试试看
如果还是不行 调整一下摄像机的z轴位置看看是不是被挡住了 或者检查一下场景的z轴位置等等
要学会自己debug 问问Google也好
