### ISSUE TITLE
微信小程序 如何安装插件

### ISSUE THREAD

**Issue by Kelsang-Metok** [buaa-soft-summer/soft-summer-2022#16]
wx.navigateTo(Object object)
在插件中使用：需要基础库 2.2.2

**Comment by echo17666** [comment]
它可能是需要小程序基础库版本不低于 2.2.2，是不是版本太低导致报错
然后安装插件可以用npm，具体可以看这里https://blog.csdn.net/yhy510858632/article/details/112259705

**Comment by Kelsang-Metok** [comment]
我明白了，其实之前报错的原因是因为代码有问题而不是少东西
不过我之前在尝试npm的过程中也搜索到过您发的这篇文章，但是在小黑框里敲入那一串字符串之后显示‘npm’不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by echo17666** [comment]
那应该是环境变量没配置好，设置一下路径就行
