### ISSUE TITLE
pygame模块写游戏，出现报错

### ISSUE THREAD

**Issue by morty-idhyuajjcbdchjdehsr** [buaa-soft-summer/soft-summer-2022#17]
Warning: Encountered more data after announced end of track (frame 25/25). Frankenstein!
写的时候出现这个报错信息，一般是哪里出了问题啊 @echo17666

**Comment by echo17666** [comment]
请问你是在声音方面出现的这个问题吗

**Comment by morty-idhyuajjcbdchjdehsr** [comment]
> 请问你是在声音方面出现的这个问题吗

有可能（我也不太清楚是哪里出问题了）

**Comment by echo17666** [comment]
你要不去查查到底是哪一部分出问题，就把没出这个报错之后写的东西一点点注释掉，看看报不报错，我查到的情况是检查一下有没有死循环，或者诸如mp3文件什么的本身有问题（如果有的话）

**Comment by morty-idhyuajjcbdchjdehsr** [comment]
> 你要不去查查到底是哪一部分出问题，就把没出这个报错之后写的东西一点点注释掉，看看报不报错，我查到的情况是检查一下有没有死循环，或者诸如mp3文件什么的本身有问题（如果有的话）
找到问题了，是一个mp3文件出了问题

**Comment by echo17666** [comment]
彳亍，查到问题就好
