### ISSUE TITLE
微信小程序request合法域名

### ISSUE THREAD

**Issue by lsysyy** [buaa-soft-summer/soft-summer-2022#18]
>
![image](https://user-images.githubusercontent.com/111101179/185053019-367f7e3d-e89c-4ce9-b406-028491e3e9ff.png)
助教给的api网址https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5好像不符合要求（该域名包含非法字符，只支持英文大小写字母、数字、“:”及“ - ”
![image](https://user-images.githubusercontent.com/111101179/185053985-a34075c8-6ea8-4300-8891-f47f4e013081.png)
然后我随便弄了个符合要求的但程序中还是显示不在域名列表中

**Comment by echo17666** [comment]
你试试看输入https://view.inews.qq.com或者https://view.inews.qq.com/g2试试看

**Comment by lsysyy** [comment]
> 你试试看输入[https://view.inews.qq.com或者https://view.inews.qq.com/g2试试看](https://view.inews.qq.com%E6%88%96%E8%80%85https://view.inews.qq.com/g2%E8%AF%95%E8%AF%95%E7%9C%8B)

呜呜好像还是不行欸，第一个符合格式跟上面一样，第二个不符合格式

**Comment by lsysyy** [comment]
> 你试试看输入[https://view.inews.qq.com或者https://view.inews.qq.com/g2试试看](https://view.inews.qq.com%E6%88%96%E8%80%85https://view.inews.qq.com/g2%E8%AF%95%E8%AF%95%E7%9C%8B)

呜呜好像还是不行欸，第一个符合格式跟上面一样，第二个不符合格式

**Comment by havesomecolo** [comment]
https://blog.51cto.com/u_15275953/4940723
看看有没有用
