### ISSUE TITLE
如何爬取网页上“元素”界面里的内容

### ISSUE THREAD

**Issue by Sillage-Shaw** [buaa-soft-summer/soft-summer-2022#19]
助教你好，我需要爬取一下往年高考的一分一段表，这是我的目标网址：https://www.gaokao.cn/colleges/bypart，我有以下几个问题：

- 在这个网页的页面源代码里面没有找到网页内的数据，而是一堆看不懂的数据
- 如何得到网页的“元素”里面的内容，如下图所示：
![image](https://user-images.githubusercontent.com/100783224/185091136-a85a12af-0b9e-4504-a682-d007c86c22c1.png)

- 如果能得到“元素”界面的内容，在我选定了特定的省份或者年份之后：
![image](https://user-images.githubusercontent.com/100783224/185091709-fab735ba-cb51-44d1-b754-ea1c43a5d0f3.png)
“元素”界面内的class属性会发生变化，然后得到新的数据，如下图所示：
![image](https://user-images.githubusercontent.com/100783224/185092139-db97b3e2-da42-4db1-971e-05f6aa7291eb.png)
那么我能否可以在爬取该页面之后通过改变某个属性得到其他年份或者是省份的数据呢，具体该怎么做呢

以上几个问题很大程度上是由于我知识面有限造成的，还望助教能帮我指出解决方法，十分感谢

**Comment by Yuan-Hou** [comment]
Python中也有一个很经典的HTML解析工具包叫BeautifulSoup，它的中文文档在 https://beautifulsoup.cn/ ，“元素”里面的内容可以用它来解析，具体怎么用做自己看看文档再搜索一些博客参考一下应该就能学会。

关于如何获取其他年份的数据，我看了一下你给的那个网站，你每切换一次年份它就会和后端进行通信，获取新的数据，具体内容你可以看看开发者工具里面的“网络”一栏，你每换一次年份它就会要过来一个新的“lists.json”，请求的URL形式类似于

> https://static-data.gaokao.cn/www/2.0/section2021/2021/11/3/1/lists.json

你模仿它的方式，用Python发起HTTP请求，应该就可以得到包含分数信息的JSON文本，然后只要解析这些JSON文本，就可以得到分数信息。
