### ISSUE TITLE
easyx中的outtextxy函数

### ISSUE THREAD

**Issue by buaabuaazk** [buaa-soft-summer/soft-summer-2022#21]
char str[10] = "re";
outtextxy(coordinate_x, coordinate_y, str);
这么写就报错： “outtextxy”: 2 个重载中没有一个可以转换所有参数类型
请问该怎么改呢

**Comment by Yuan-Hou** [comment]
你的coordinate_x和coordinate_y都是什么数据类型？

**Comment by buaabuaazk** [comment]
int型的

**Comment by buaabuaazk** [comment]
改成outtextxy(coordinate_x, coordinate_y, L"re");就能正常运行

**Comment by woarthur** [comment]
试试把char str[10]改成char* str呢

**Comment by buaabuaazk** [comment]
VS好像不支持char* str=“re”这种写法，
不过解决了，在属性里把“Unicode字符集”改成“多字节字符集”就行了，
谢谢助教
