### ISSUE TITLE
请问JFrame中如何进行延迟操作？

### ISSUE THREAD

**Issue by hany01rye** [buaa-soft-summer/soft-summer-2022#22]
首先我写的两个主要的class是`public class LoginJFrame extends JFrame implements MouseListener`用于做登录界面和`public class SelectJFrame extends JFrame implements MouseListener`用于做随机对手和选择英雄的界面。
我的总流程是：先`new LoginJFrame()`，在构造函数中实现登录界面，如果登录成功，则会直接在`LoginJFrame`中调用`new SelectJFrame()`。
我想实现的是随机对手的画面，每个BOSS的图片出现200ms、不断切换十几次后再随机一个BOSS显示。随机后再显示选择英雄的画面。
关于切换BOSS的函数我是这么写的（`randomView(int enemyID)`即在JFrame中`removeALL()`、重新`add()`当前BOSS、然后`repaint()`）：
```java
    public void randomEnemy() {
        for (int i = 0; i < 15; ++ i) {
            randomView(i % 3);
            try {
                sleep(300);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
```
得到的效果是前面切换BOSS的时间一直是一个空窗口，直到选择英雄的窗口才出现画面。
但是如果我在Test.class中直接`new SelectJFrame()`而不是`new LoginJFrame()`后在`LoginJFrame`中调用`SelectJFrame`，切换画面就不会出现问题。
所以我想问一下为什么会出现这种情况，以及怎么处理延时才不会出现线程问题。

**Comment by hany01rye** [comment]
现在改成了每次用`graphics` `repaint()`。
问题已解决。
所以请问有人知道上面的代码为什么会出问题吗qwq

**Comment by Yuan-Hou** [comment]
swing里面有个东西叫作timer可以试一试?

**Comment by hany01rye** [comment]
> swing里面有个东西叫作timer可以试一试?

好的蟹蟹~
