### ISSUE TITLE
unity运行报错

### ISSUE THREAD

**Issue by SAGADESU** [buaa-soft-summer/soft-summer-2022#23]
![949331fdef2804892bc89bcd554a122](https://user-images.githubusercontent.com/111098074/185369516-950c46de-c7f0-47a0-b0e4-4fa43808c6a9.jpg)

**Comment by woarthur** [comment]
unity官方的解答
https://forum.unity.com/threads/the-property-database-library-search-propertydatabase-db-is-already-opened.1285634/
如果解决不了可以尝试重启你的电脑（

**Comment by SAGADESU** [comment]
嗯，重启以后解决了
