### ISSUE TITLE
在django中，怎么实现 局部更新数据表展示的顺序呢？

### ISSUE THREAD

**Issue by andakai** [buaa-soft-summer/soft-summer-2022#25]
比如有“推荐 热门 时间”这三个导航按钮，点击“时间”后，数据表展示时按照时间的顺序，点击“热门”后，数据表按照浏览量展示。
`views.py`文件中
![image](https://user-images.githubusercontent.com/77474977/185554694-f4f91736-1bda-4bc5-9c83-a1f5b5cfaebb.png)
`html`文件中
![image](https://user-images.githubusercontent.com/77474977/185554772-9dc33800-cbe1-4bac-9624-5c04f80eae41.png)
我了解到有Ajax能实现部分页面的刷新，但只知道能在不刷新页面的时候传递数据，但这种涉及到数据表的能改吗？（实在不行就再多写点页面了
@fish-heshui @LLLeoLi

**Comment by Yuan-Hou** [comment]
你可以在problem_set函数里面多来一个url参数，表明希望数据怎样排列，然后在后续处理中按照参数进行排序并渲染。网页中相应的按钮直接跳到相应参数的url。

或者，你也可以通过前端的js脚本，在同一个页面中实现，js里关于给列表排序的函数是sort，你可以给它提供一个回调函数来确定偏序关系。

**Comment by Yuan-Hou** [comment]
实现这个功能不至于使用Ajax，因为你这个程序里，前端一次请求就把所有需要的数据给要回来了，接下来仅仅是展示形式发生了变化。

不刷新而改变页面内容属于ajax里面使用到的一个js的功能，ajax本身是几个技术的合称，常被拿来指代它们结合起来能实现的效果。

想不刷新而改变页面内容，可以参考[如何通过JavaScript来查找并修改dom](https://www.w3school.com.cn/js/js_htmldom.asp)，这属于JavaScript的功能。

**Comment by Yuan-Hou** [comment]
可以参考这里提到的第二种方法

https://blog.csdn.net/u011138533/article/details/72629728
