### ISSUE TITLE
Android 中 getcolumnIndex返回值报错，请问有什么解决办法嘛

### ISSUE THREAD

**Issue by xfy-mufc** [buaa-soft-summer/soft-summer-2022#26]
我是这样写的：
private static final String COLUMN_MONEY = "money“；
后来这样调用时：
float money = cursor.getFloat(cursor.getColumnIndex(COLUMN_MONEY));
出现了报错信息：
Value must be ≥ 0 but `getColumnIndex` can be -1

**Comment by fish-heshui** [comment]
COLUMN_MONEY列是不是应该写为‘COLUMN_MONEY’，或者检查一下列名有没有写错

**Comment by xfy-mufc** [comment]
> COLUMN_MONEY列是不是应该写为‘COLUMN_MONEY’，或者检查一下列名有没有写错

运行时发现这个错误好像对运行没有影响，程序可以运行，然后照着这个方法改然报错。为啥呀emmmmmm

**Comment by fish-heshui** [comment]
`@SuppressLint("Range") float money = cursor.getFloat(cursor.getColumnIndex('COLUMN_MONEY'));`
尝试一下这样写？我不会安卓开发，运行也没有影响的话，依据java理解可能是想要catch一下可能出现的运行时错误吧(?:shit:

**Comment by xfy-mufc** [comment]
> `@SuppressLint("Range") float money = cursor.getFloat(cursor.getColumnIndex('COLUMN_MONEY'));` 尝试一下这样写？我不会安卓开发，运行也没有影响的话，依据java理解可能是想要catch一下可能出现的运行时错误吧(?💩

这样改确实不报错了，但是运行时报错说：Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.，能麻烦看一下嘛QAQ

**Comment by fish-heshui** [comment]
试着用getColumns函数获取一下所有列名吧，感觉应该是列不存在报错的（不好意思刚刚我也在写代码qaq

**Comment by fish-heshui** [comment]
同学们注意一下变量命名规范，统一下划线or驼峰，不要使用相似的变量名（stu_id & stu_Id），减少bug
