### ISSUE TITLE
pygame 如何使用pyinstaller 打包多个不同级文件成为exe文件

### ISSUE THREAD

**Issue by XenonGa** [buaa-soft-summer/soft-summer-2022#27]
![image](https://user-images.githubusercontent.com/111100012/185736998-37e7ca38-1071-497a-992c-9d36fbf126bf.png)
![image](https://user-images.githubusercontent.com/111100012/185737005-56779b83-5d08-4956-98b0-05ae5abe2e8f.png)
![image](https://user-images.githubusercontent.com/111100012/185737011-86290420-6b2a-4c0d-b7de-e2a935a4bfce.png)
![image](https://user-images.githubusercontent.com/111100012/185737025-aefd5a8c-135a-42f4-a815-179d2dc434fa.png)
![image](https://user-images.githubusercontent.com/111100012/185737048-9fc43b20-14ae-453f-9b51-8f05e02ddf83.png)
如上图，我的各种py文件放置在不同文件夹内，图片与音乐等资源文件放置在resources文件夹中，并且我还引用了json文件，用pyinstaller打包了几次都没有成功，求解决方法TAT

**Comment by echo17666** [comment]
打包最外面一层启动游戏的py文件就行，然后记得把这些图片音乐资源的文件放到同级的目录下面。

**Comment by XenonGa** [comment]
就是说把图片这些资源直接放到目录里还是可以把文件夹放到这个同级的目录呢

**Comment by echo17666** [comment]
可以把包含资源的文件夹放到和.exe的同级目录里面

**Comment by XenonGa** [comment]
![image](https://user-images.githubusercontent.com/111100012/185754453-e1d7b3df-c883-4eb1-9af1-b94f1e54fb7a.png)
我把包含资源的文件夹放到了dist文件夹里，然后点main.exe还是会闪退，不知道啥情况TAT
打包的时候输入的是pyinstaller main.py

**Comment by echo17666** [comment]
闪退的话可能是打包的时候有问题，如果是读取不到资源会弹出资源读取不到的错误框框
我记得好像不应该是oyinstaller main.py这么简单
可以参考一下这篇文章https://zhuanlan.zhihu.com/p/165431703
我隐约记得打包多个文件应该是pyinstaller -D xxx

**Comment by echo17666** [comment]
https://zhuanlan.zhihu.com/p/165431703

**Comment by XenonGa** [comment]
![image](https://user-images.githubusercontent.com/111100012/185771947-8b940100-3a44-48bc-825e-f1df4ebaa17a.png)
截到这个，一个是他找不到我的json文件，这个我会把json文件里的东西写到py文件里≡(▔﹏▔)≡
最后一行不知道是啥意思，就这几行出来之后直接闪退

**Comment by echo17666** [comment]
我记得打包的时候会在文件夹里面生成一个html文件，那里面会说明打包具体的问题
还有一种可能是代码本身的问题，或者说代码目录结构不合理什么的，导致打包的时候出错。

**Comment by echo17666** [comment]
我记得打包的时候会在文件夹里面生成一个html文件，那里面会说明打包具体的问题
还有一种可能是代码本身的问题，或者说代码目录结构不合理什么的，导致打包的时候出错。

**Comment by XenonGa** [comment]
噢噢噢改了json文件直接就可以运行了（虽然有的时候不知道为啥还闪退一下
总之谢谢学长啦\(^0^)/
