### ISSUE TITLE
自己写的这个py模块为什么调用不了

### ISSUE THREAD

**Issue by purple-poi** [buaa-soft-summer/soft-summer-2022#28]
@echo17666
我写了一个.py文件，然后在另一个文件里也通过from...import...声明了，为啥在这个下面调用的时候就不能调用了呢

**Comment by echo17666** [comment]
我记得调用文件直接import xxx就行了
如果调用出问题可以看看是不是写的时候语法有问题什么的

**Comment by purple-poi** [comment]
<img width="362" alt="1661048287193" src="https://user-images.githubusercontent.com/109514806/185772483-cc5dfbf6-c464-4cdb-831e-6c57d900cfe2.png">
然后
<img width="288" alt="1661048361327" src="https://user-images.githubusercontent.com/109514806/185772510-d3bb361a-0439-43e8-b227-49138e5aa5ad.png">
在这个main.py开头进行了声明，但是我写到这里
<img width="242" alt="1661048469459" src="https://user-images.githubusercontent.com/109514806/185772564-4917f5aa-cf5c-4992-ac0f-838d42c834ed.png">
<img width="461" alt="069404d02267c17b13fd567bab83e7e" src="https://user-images.githubusercontent.com/109514806/185772568-b58717ba-c5e6-44fb-8ea9-8de0be2949b3.png">
发现没有我需要的，不太明白这一点

**Comment by echo17666** [comment]
我猜测应该是from import写的有问题
你试试直接改成import tetrisOperate试试看

**Comment by RyouonRitsu** [comment]
import 模块
模块.函数()
from 模块 import 函数/类
函数/类()
你看看你有没有遵循这个规则
以及如果是函数返回值的实例属性或者实例方法没有你需要的 可以查看一下对应的实例中的属性或方法是不是public的 有没有暴露给外部模块或文件
