### ISSUE TITLE
有关小程序布局的小问题

### ISSUE THREAD

**Issue by BUAAkang** [buaa-soft-summer/soft-summer-2022#29]
在支持flex的<view>块中无法修改button尺寸，代码如下
index.wxss
```
.container{
  width: 100%;
  box-sizing: border-box;
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.button{
  background-color: #22cc22;
  color: white;
  font-size: small;
  width: auto;
  /*testdata: 200rpx, 2cm, 20%...*/
}
```
index.wxml
```
<view class="container">
  <input placeholder="输入你的内容"/>
  <button class="button">提交</button>
</view>
```
![Snipaste_2022-08-21_11-57-22](https://user-images.githubusercontent.com/111173291/185775588-05ce1b78-bb65-4387-890e-1b6e67823b85.png)

如图，button宽度在所有测试数据下均不改变

附：在weui的组件渲染下未达到预期效果，自己贸然修改会产生大量问题（如上）
因此请教下这种情况该如何处理？
又或该怎么获取weui组件的数据（如16进制色值），以便在自编的wxss中尽量达到风格上的贴合？

**Comment by leileidesu** [comment]
你可以看看这个
https://blog.csdn.net/hjiaqing/article/details/102991201
可以完美解决你的问题

![b2001ece2425960bb989714247f08ed](https://user-images.githubusercontent.com/89326928/185784555-8f9a95de-58bc-4563-9c30-391faed89795.png)

在我看来，可以不用button，可以把view做得像button的样子，更灵活一些，同样也可以使用bindtap属性。

**Comment by BUAAkang** [comment]
懂了，谢谢助教
还想问一下怎样可以让顶部的任务添加栏不参与下拉，保持位置绝对性？
![Snipaste_2022-08-21_18-56-18](https://user-images.githubusercontent.com/111173291/185787976-9791463d-c681-4ea5-864b-7ad838b960e1.png)
（好像设置position属性四种选项都不太行……）

**Comment by leileidesu** [comment]
感觉可以这样，比如整个屏幕高100vh，你希望他不参与滚动的上面的区域viewA比如是20vh，那就把下面剩下的80vh设成一个viewB，高度固定80vh，属性overflow-y:auto，那就只有下面的viewB可以在80vh的区域里滚动，整个屏幕不会滚动（因为20vh+80vh加起来正好是一个屏幕长，所以不会溢出），大概类似这样

**Comment by BUAAkang** [comment]
懂了，谢谢助教！
