### ISSUE TITLE
exe文件无法运行

### ISSUE THREAD

**Issue by Sillage-Shaw** [buaa-soft-summer/soft-summer-2022#34]
助教你好，我在使用Pycharm导出exe文件的时候运行错误，打开的时候弹出了这个窗口：
![image](https://user-images.githubusercontent.com/100783224/185908567-c6ce351a-5263-468b-9c7e-7b1809f26a04.png)
我在Python编辑器下可以正常运行，但是exe文件打开就出现了这个窗口，我想的是我虚拟环境的模块可能有问题，但弄了好久也没有解决，希望能给点建议，谢谢

**Comment by RyouonRitsu** [comment]
你在打包的时候加上参数 *--path Python安装目录下的lib文件的路径* 试试
