### ISSUE TITLE
打包py文件时出现notanexecuable，exe文件打不开

### ISSUE THREAD

**Issue by OrsonZane** [buaa-soft-summer/soft-summer-2022#35]
Hi,@echo17666

问题：
我的pygame文件中只导入了图片文件，且所有图片格式均为.png，是因为没有把图片一起打包吗？
现在已学会将图片格式转换为.py文件，但还是不清楚怎么将pygame转换成可执行文件。

环境：
pygame 2.1.2 (SDL 2.0.18, Python 3.10.6)

系统：
win11

**Comment by echo17666** [comment]
不需要打包图片，只需要把py文件打包成exe文件，然后把图片放到同级目录下即可
