### ISSUE TITLE
Unity游戏素材

### ISSUE THREAD

**Issue by smth107** [buaa-soft-summer/soft-summer-2022#6]
@RyouonRitsu 想做一个3D游戏，但找不到合适的素材，尤其缺少角色、NPC、怪物这些的模型和动画，asset store上这些也很少有免费的，请问还可以去哪找呢

**Comment by RyouonRitsu** [comment]
有关素材方面，可以考虑像素风，使用类似我的世界的模型素材，这些可以自己建模和调整动画，是最简单的素材了，也可以看看有没有类似的模型商店之类的。如果素材实在获取困难，建议换用u2d，2d素材获取难度较小，同样也是像素风的素材最容易获取，也可以尝试解包现有的游戏获取素材。如果以上都不行，那就建议换个选题，不建议在自己没有足够素材的情况下制作游戏。

**Comment by Yuan-Hou** [comment]
3D建模我推荐一个小软件叫Magicvoxel，它是一款体素风格的建模软件，用起来感觉跟玩Minecraft一样。这种风格的模型如果要做动画，可以只做一个弹跳，观感也很不错。

**Comment by Yuan-Hou** [comment]
3D建模我推荐一个小软件叫Magicvoxel，它是一款体素风格的建模软件，用起来感觉跟玩Minecraft一样。这种风格的模型如果要做动画，可以只做一个弹跳，观感也很不错。
