### ISSUE TITLE
unity packages异常

### ISSUE THREAD

**Issue by luochuan706** [buaa-soft-summer/soft-summer-2022#8]
按照正常流程下载unity后，打开新项目出现报错
<img width="350" alt="微信截图_20220814160316" src="https://user-images.githubusercontent.com/111209466/184528153-c529d698-d28a-4c38-af52-9e7073831630.png">
package manager界面显示如下
<img width="600" alt="微信截图_20220814160429" src="https://user-images.githubusercontent.com/111209466/184528171-ae88374a-6245-4171-b111-3ab2c82e0bb7.png">
尝试了很久都没有解决，包括重装unity，更换unity版本等。
@RyouonRitsu

**Comment by RyouonRitsu** [comment]
你的目录里是不是有非法符号之类的？空格，中文等等

**Comment by RyouonRitsu** [comment]
如果不是因为这个的话 应该是环境出问题了 去搜索引擎搜索一下有没有类似的问题看看 如果还是不能解决 重装系统吧
