### ISSUE TITLE
微信小程序 全局变量使用

### ISSUE THREAD

**Issue by Quinsai** [buaa-soft-summer/soft-summer-2022#9]
![picture1](https://user-images.githubusercontent.com/103517967/184570141-24fe4c55-55ff-45f5-b9ae-f6175358cb52.png)
像这个里面一样，设定了两个全局变量在app.js.globalData中
![p2](https://user-images.githubusercontent.com/103517967/184570243-a30d7b2b-4c7e-4288-80f0-c9d08b422730.png)
![p4](https://user-images.githubusercontent.com/103517967/184570249-e066580b-f724-4a3c-a8d6-1067d6ef8cab.png)
然后先给它赋值，后面在拿出来用
![p3](https://user-images.githubusercontent.com/103517967/184570302-a878a60c-3161-4e84-b213-833aef1e0c0e.png)
但从console来看，之前已经赋好值的，在下一个页面以来又不见了

**Comment by echo17666** [comment]
有没有可能，赋值的时候是在index.js界面，但是你先进的是new Position界面，这时候globalData还是空的？

**Comment by Quinsai** [comment]
不知道是不是这个原因，但当我把赋值语句放在index.js的onLoad中时，问题就被解决了
